### ISSUE TITLE
Table Support

### ISSUE THREAD

**Issue by Redcof** [Redcof/ints-jst#4]
The library does not support table.

**Comment by Redcof** [comment]
This can be solved using css below:
```css
/** <js-t> table CSS support  */
        .table {
            display: table;
            width: 100%;
        }

        .thead {
            display: table-row-group;
        }

        .th {
            display: table-cell;
            font-weight: bold;
        }

        .tbody {
            display: table-row-group;
        }

        .tr {
            display: table-row;
        }

        .td {
            display: table-cell;
        }
```
